### ISSUE TITLE
Set up the map interface with geographical regions

### ISSUE THREAD

**Issue by loganDoran** [ishraqn/CGC-DataVizTool#1]
**Description**: 
Create a map interface displaying geographical regions, including provinces and agricultural zones.

**Tasks**:
- [x] Integrate a mapping library/framework supporting shape file rendering 
- [x] Load shape files for provinces, and agricultural zones.
- [x] Design user interface elements for map interaction.

**Acceptance Criteria**:
- The map interface is rendered without errors or inconsistencies.
- Geographical data for provinces and agricultural zones are accurately loaded and displayed on the map interface.
- Province and Agricultural zone boundaries are clearly delineated and visually distinguishable.
- User interface elements for map interaction are implemented and functional.
- The user interface is responsive and adapts seamlessly to different screen sizes and devices.

**Notes**:
- For map integration look into and consider a combination of Leaflet-Geoman, Leaflet, and `shapefile` library in Node.js.
